version: '3'
services:
  web:
    image: "prestashop/prestashop:1.7"
    container_name: "peinau_prestashop_1_7"
    env_file: .env
    ports:
      - "8000:80"
    depends_on:
      - mysql
    environment:
      - DB_SERVER=peinau_mysql
    volumes:
    - .:/var/www/html/modules/peinau
  mysql:
    image: mysql
    container_name: peinau_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-admin}
